#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
USE_PROCD=1
START=99

prog_name="QUICTun"
bin="/usr/bin/QUICTun"
tmp_folder="/tmp/$prog_name"

write_opt() {
    cfg_func="$1"
    opt_func="$2"

    val_func=""
    config_get val_func "$cfg_func" "$opt_func"
    [ -n "$val_func" ] && echo "$opt_func = $val_func" >>"$conf"
}

instance_parse() {
    cfg="$1"

    enabled=""
    config_get_bool enabled "$cfg" enabled 1
    [ "$enabled" -eq 1 ] || return 0

    mkdir -p "$tmp_folder"
    conf="$tmp_folder/$cfg.conf"

    true >"$conf"

    write_opt "$cfg" QuicEndpoint
    write_opt "$cfg" WgListen
    write_opt "$cfg" CertsPath
    write_opt "$cfg" LogPath
    write_opt "$cfg" StatPath
    write_opt "$cfg" SNI
    write_opt "$cfg" QuicListen
    write_opt "$cfg" WgEndpoint

    procd_open_instance "$cfg"
    procd_set_param command "$bin"
    procd_append_param command "$conf"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

start_service() {
    config_load "$prog_name"

    if [ -n "$1" ]; then
        instance_parse "$1"
    else
        config_foreach instance_parse instance
    fi
}

service_triggers() {
    procd_add_reload_trigger "$prog_name"
}
